[[constraint]]
  name = "k8s.io/api"
  branch = "release-1.12"

[[constraint]]
  name = "k8s.io/apimachinery"
  branch = "release-1.12"

[[constraint]]
  name = "k8s.io/client-go"
  branch = "release-9.0"
