apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: kube-git-build
  #generateName: kube-git-build-
  namespace: ci
spec:
  ttlSecondsAfterFinished: 3600
  entrypoint: kube-git-build
  arguments:
    parameters:
    - name: branch
      value: master
    - name: revision
      value: master
    - name: kubegitRepo
      value: https://github.com/appwavelets/kube-git.git
  serviceAccountName: argo-appwavelets
  templates:

  - name: kube-git-build
    steps:
    - - name: build-code
        template: build-code

  - name: build-code
    inputs:
      artifacts:
      - name: kube-git
        path: /go/src/github.com/appwavelets/kube-git
        git:
          repo: "{{workflow.parameters.kubegitRepo}}"
          revision: "{{workflow.parameters.revision}}"
    container:
      image: "abdullahalmariah/cloud-tools:latest"
      command: [sh, -c]
      args: ["until docker ps; do sleep 3; done; echo ready &&
              docker build -t abdullahalmariah/kube-git:latest . &&
              echo $DOCKER_PASSWORD | docker login -u abdullahalmariah --password-stdin &&
              case {{workflow.parameters.branch}} in
              refs/tags/*)
                RELEASE=$(echo {{workflow.parameters.branch}} | cut -c11-)
                docker push \"abdullahalmariah/kube-git:$RELEASE\"
                ;;
              refs/heads/master)
                docker push abdullahalmariah/kube-git:latest
                ;;
              esac"]
      env:
      - name: DOCKER_HOST
        value: tcp://localhost:2375
      - name: DOCKER_PASSWORD
        valueFrom:
          secretKeyRef:
            name: docker-secret-abdullahalmariah
            key: password
      workingDir: /go/src/github.com/appwavelets/kube-git
      resources:
        limits:
          memory: 2Gi
          cpu: 1
        requests:
          memory: 2Gi
          cpu: 1
    sidecars:
    - name: dind
      image: docker:17.10-dind
      securityContext:
        privileged: true
      resources:
        limits:
          memory: 2Gi
          cpu: 1
        requests:
          memory: 2Gi
          cpu: 1
