apiVersion: kubegit.appspero.com/v1alpha1
kind: GitHook
metadata:
  name: kube-git
  namespace: ci
spec:
  repository: https://github.com/appspero/kube-git.git
  branches:
    - "*"
  manifest: examples/argo.yaml
  timestampSuffix: true
  argoWorkflow:
    revisionParameterName: revision
    branchParameterName: branch
  notification:
    slack: appspero-ci
