apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: githooks.kubegit.appwavelets.com
spec:
  group: kubegit.appwavelets.com
  version: v1alpha1
  names:
    kind: GitHook
    plural: githooks
    singular: githook
    shortNames:
    - gh
  scope: Namespaced
  subresources:
    status: {}
  additionalPrinterColumns:
    - name: Repository
      type: string
      description: The git repository of the GitHook
      JSONPath: .spec.repository
    - name: Trigger Count
      type: string
      description: The triggering count of the GitHook since creation
      JSONPath: .status.triggerCount
    - name: Last Trigger
      type: date
      description: The triggering count of the GitHook since creation
      JSONPath: .status.lastTrigger
    - name: Age
      type: date
      JSONPath: .metadata.creationTimestamp
  validation:
    openAPIV3Schema:
      properties:
        spec:
          properties:
            repository:
              type: string
            branches:
              items:
                type: string
              type: array
            manifest:
              type: string
            timestampSuffix:
              type: boolean
            argoWorkflow:
              properties:
                revisionParameterName:
                  type: string
                branchParameterName:
                  type: string
            usernameSecret:
              properties:
                name:
                  type: string
                key:
                  type: string
              required:
                - name
                - key
            passwordSecret:
              properties:
                name:
                  type: string
                key:
                  type: string
              required:
                - name
                - key
            sshPrivateKeySecret:
              properties:
                name:
                  type: string
                key:
                  type: string
              required:
                - name
                - key
            notification:
              properties:
                github:
                  type: string
                slack:
                  type: string
          required:
            - repository
            - branches
            - manifest
