apiVersion: v1
kind: Service
metadata:
  labels:
    k8s-app: kube-git
  name: kube-git
  namespace: default
spec:
  ports:
  - name: webhook
    port: 80
    targetPort: 8080
  selector:
    k8s-app: kube-git
